---
- name: Install basic packages
  dnf:
      name:
        - bash-completion
        - dstat
        - htop
        - screen
        - tmux
        - tree
        - gcc
        - redhat-rpm-config
        - python-devel
        - poetry
        - libpq-devel
        - gcc
        - fedora-messaging
      state: present
