name: Clean Stale Issues And Pull Requests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v9.0.0
        with:
          exempt-all-assignees: true
          # exclude issues/PRs with the specified labels
          exempt-issue-labels: good-first-issue,todo
          stale-issue-message: "This issue is stale because it has been open for 60 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 7 days since being marked as stale."
          operations-per-run: 1000
